// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7m0DMcVGqYjiUhKhKr0zHMoac-Lj_Is',
    appId: '1:230355024122:web:940c577ddc26078157f143',
    messagingSenderId: '230355024122',
    projectId: 'migraayuda-fb971',
    authDomain: 'migraayuda-fb971.firebaseapp.com',
    storageBucket: 'migraayuda-fb971.firebasestorage.app',
    measurementId: 'G-FYLMVKF8Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS9dWZSewXldqcf4jWbNCKzzP_OsjG6zw',
    appId: '1:230355024122:android:529414eae9fb827a57f143',
    messagingSenderId: '230355024122',
    projectId: 'migraayuda-fb971',
    storageBucket: 'migraayuda-fb971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpzTw_4-2S2AvDyE0yIX4h9_yX7sesdFg',
    appId: '1:230355024122:ios:c00ea12627416b3557f143',
    messagingSenderId: '230355024122',
    projectId: 'migraayuda-fb971',
    storageBucket: 'migraayuda-fb971.firebasestorage.app',
    iosBundleId: 'com.example.migraAyuda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpzTw_4-2S2AvDyE0yIX4h9_yX7sesdFg',
    appId: '1:230355024122:ios:c00ea12627416b3557f143',
    messagingSenderId: '230355024122',
    projectId: 'migraayuda-fb971',
    storageBucket: 'migraayuda-fb971.firebasestorage.app',
    iosBundleId: 'com.example.migraAyuda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo7m0DMcVGqYjiUhKhKr0zHMoac-Lj_Is',
    appId: '1:230355024122:web:bea29ebda980e0b557f143',
    messagingSenderId: '230355024122',
    projectId: 'migraayuda-fb971',
    authDomain: 'migraayuda-fb971.firebaseapp.com',
    storageBucket: 'migraayuda-fb971.firebasestorage.app',
    measurementId: 'G-VW6B3ZKBCN',
  );
}
