class ListCountries {
  static contries() => [
        'México',
        'Estados Unidos',
        'Canadá',
        'Guatemala',
        'Honduras',
        'El Salvador',
        'Nicaragua',
        'Costa Rica',
        'Panamá',
        'Cuba',
        'Jamaica',
        'Haití',
        'República Dominicana',
        'Puerto Rico',
        'Trinidad y Tobago',
        'Barbados',
        'Santa Lucía',
        'San Vicente y las Granadinas',
        'Granada',
        'Antigua y Barbuda',
        'Dominica',
        'San Cristóbal y Nieves',
        'Bahamas',
        'Colombia',
        'Venezuela',
        'Ecuador',
        'Perú',
        'Bolivia',
        'Brasil',
        'Chile',
        'Argentina',
        'Uruguay',
        'Paraguay',
        'Guyana',
        'Surinam',
        'Belice',
      ];
}
